org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.2
modmenu_version=20.0.1

mod_id=lush_grass
mod_name=LessLush Grass
mod_version=1.4.3b
artifact_version_suffix=fabric+mc26.2
mod_group_id=com.github.kryvii
mod_authors=LieutenantKhaos
archives_base_name=less_lush_grass
